services:
  db:
    image: mysql:8.4
    restart: always
    container_name: db
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: prisma
      MYSQL_USER: prisma
      MYSQL_PASSWORD: prisma
      MYSQL_DATABASE: myfin_tests
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
  check-db-started:
    image: jwilder/dockerize:0.6.1
    depends_on:
      db:
        condition: service_healthy
    command: 'dockerize -wait=tcp://db:3306 -timeout 30s'